{% set name = "goes2go" %}
{% set version = "2025.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9025f51c0299d6ab422666540dbc2f3259a6e52f09672b8034413dea256b33a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - PYTHONIOENCODING=utf8

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm

  run:
    - cartopy
    - h5netcdf
    - metpy
    - netcdf4
    - numpy
    - pandas
    - python >={{ python_min }}
    - pygrib
    - s3fs
    - toml
    - xarray

test:
  commands:
    - pip check
  imports:
    - goes2go
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/blaylockbk/goes2go
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Retrieve GOES-East/West data from AWS. RGB recipes included!
  description: |
    GOES-East and GOES-West satellite data are made available on Amazon Web
    Services through NOAA's Big Data Program. `goes2go` is a python package
    that makes it easy to find and download the files you need to your local
    computer. Some additional helpers are provided that make working with GOES
    data easy and fun, such as recipes for RGB composites.
  doc_url: https://goes2go.readthedocs.io/
  dev_url: https://github.com/blaylockbk/goes2go

extra:
  recipe-maintainers:
    - blaylockbk
